### ISSUE TITLE
NotFound error when tests ran without specific package context

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#2056]
When I run something like:

```bash
cargo test -p azure_security_keyvault_secrets
// or
cargo test -p azure_security_keyvault_secrets --test secret_client
// or
cargo test -p azure_security_keyvault_secrets --test secret_client secret_roundtrip
```

Or even click the "Run Test" chevron in VSCode, playback tests pass; however, if I drop `-p azure_security_keyvault_secrets` tests fail.

Probably lacking context, though I would think `cargo` would do that regardless. Apparently not. Will have to debug to learn more.

**Comment by heaths** [comment]
After refactoring a bunch of tracing, I noticed in the manually-started test-proxy when running tests for the whole workspace:

```
      Executed endpoint 'Azure.Sdk.Tools.TestProxy.Playback.HandleRequest (Azure.Sdk.Tools.TestProxy)'
[19:22:25] fail: Azure.Sdk.Tools.TestProxy[0]
      Unable to find a record for the request POST https://Sanitized.vault.azure.net/keys/encrypt-decrypt/create?api-version=7.6-preview.2
      Header differences:
          <Accept-Encoding> is absent in record, value <gzip>
      Body differences:
      Remaining Entries:
      0: https://Sanitized.vault.azure.net/keys/encrypt-decrypt/create?api-version=7.6-preview.2
      1: https://Sanitized.vault.azure.net/keys/encrypt-decrypt/e4cb88ca838b4f869ac495bb466a71e7/encrypt?api-version=7.6-preview.2
      2: https://Sanitized.vault.azure.net/keys/encrypt-decrypt/e4cb88ca838b4f869ac495bb466a71e7/decrypt?api-version=7.6-preview.2
```

I wasn't seeing that for successful requests. Sure enough, if I add `Accept-Encoding: gzip` into some recorded sessions manually, the tests pass.

This appears to be because of the `reqwest_gzip` feature that, when building the workspace, is part of the default feature set for `typespec_client_core`; however, `azure_security_keyvault_secrets`, for example, defines:

```toml
[dependencies]
azure_core = { workspace = true }
# ...
typespec_client_core = { workspace = true, features = ["derive"] }
```

While the workspace `Cargo.toml` defines those as:

```toml
[workspace.dependencies.azure_core]
version = "0.22.0"
path = "sdk/core/azure_core"

# ...

[workspace.dependencies.typespec_client_core]
path = "sdk/typespec/typespec_client_core"
version = "0.1.0"
default-features = false
```

`azure_core`'s `Cargo.toml`, in turn, defines:

```toml
[dependencies]
typespec_client_core = { workspace = true, features = ["http", "json"] }
# ...

default = []
azurite_workaround = []
# ...
reqwest = ["typespec_client_core/reqwest"]
reqwest_gzip = ["typespec_client_core/reqwest_gzip"]
reqwest_rustls = ["typespec_client_core/reqwest_rustls"]
```

Thus, only when we compile the workspace is the `reqwest_gzip` feature enabled. Off hand, I don't recall why we disable default features from `typespec_client_core` in the workspace `Cargo.toml` for all crates, but it seems we need to decide what to enable by default or even unconditionally.

@JeffreyRichter is there any reason we *should not* enable gzip by default? The computation for zipping should be miniscule compared to the network IO sending uncompressed data across the wire. I mean, we encrypt over the wire without even thinking about it and have for a couple decades (it was expensive back in the day).

**Comment by heaths** [comment]
Introduced in #1710, though it's not clear why the features are disabled by default. Perhaps because not all our crates need HTTP, though very few.

@LarryOsterman would it make sense for non-HTTP (for now, just AMQP) to disable default features? If someone is using your crates and only your crates, those features shouldn't be enabled but building the entire workspace they would be. Which is what happens anyway because cargo uses a union of features: <https://doc.rust-lang.org/cargo/reference/features.html#feature-unification>.

I'm leaning this way. Let crates opt out of default features and we should still end up with the right result e.g.,

```toml
[dependencies]
typespec_client_core = { workspace = true, default-features = false }
```
