### ISSUE TITLE
Run `cargo-deny` in pipeline to check for violations before CG

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#2091]
We should be installing and running `cargo-deny` in our PR pipelines to catch issues early e.g.,

```toml
[bans]

# must use openssl
[[bans.deny]]
name = "rustls"

# unapproved cryptographic crate
[[bans.deny]]
name = "ring"
```
