### ISSUE TITLE
Enable builds using internal package feeds

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-rust#2397]
To ensure code works with private feeds we need to build packages using the internal private feeds.

**Comment by heaths** [comment]
We need to do this to enable Oxidizer coverage anyway.

**Comment by heaths** [comment]
We can [add a registry](https://doc.rust-lang.org/cargo/reference/registries.html) as described in Azure Artifacts:

```toml
[registries]
azure-sdk = { index = "sparse+https://pkgs.dev.azure.com/azure-sdk/_packaging/azure-sdk-for-rust/Cargo/index/" }
```

To _always_ override https://crates.io, we can replace its source with ours:

```toml
[source.crates-io]
replace-with = "azure-sdk"
```

Allegedly, if the feed already has upstream sources pulled locally, it should work for externals meaning we could keep it like this. The only problem is if a customer needs to add or update a dependency, they couldn't unless they pass `--registry crates-io` (need to test this).

But it also means that we need to authenticate to pull upstream packages since anonymous uses can't, which means [installing the credential provider](https://doc.rust-lang.org/cargo/reference/registry-authentication.html):

```sh
cargo install --locked artifacts-cargo-credprovider
```

This uses wincred on Windows, keyring on macOS, and libsecret on linux, which means in WSL I had to run:

```sh
sudo apt install libsecret-1-0
```

But alone, it does nothing. You have to install GNOME keyring or something, which requires Weyland or some Xorg-compatible desktop, as well as `dbus`. There are some options described here: <https://github.com/microsoft/WSL/issues/4254>

Alternatively, I already have a separate 1Password vault for work-related stuff so, at least as a test, I installed [`cargo-credential-1password`](https://crates.io/crates/cargo-credential-1password) and set up `~/.cargo/config.toml`:

```sh
cargo install --locked cargo-credential-1password
```

```toml
[registry]
global-credential-providers = ["cargo-credential-1password --vault Microsoft"]
```

But that looks for `op` in WSL, and I've never had luck bridging `op` in WSL to 1Password running in Windows. In fact, all their recent SSH auth/signing docs have you configure `~/.gitconfig` to point to `op.exe` in Windows, so - finding no configuration for their credential provider - I just made a symlink:

```sh
ln -s $(which op.exe) ~/bin/op
```

To pull packages initially, you need to create a PAT with the `Packaging : Read+Write` scope that you paste in when prompted and can then pull packages.

```sh
cargo login --registry azure-sdk
cargo build --all-targets
```

**Comment by heaths** [comment]
1Password is prompting me to authenticate, but after I paste a PAT in, nothing happens. I've tried a couple times, pressed `Enter` a couple more times after pasting the PAT, etc.

The public `artifacts-cargo-credprovider` I installed from crates.io seem broken. Said it couldn't deserialize "hello" (handshake). But if I follow internal docs, I can install it like so:

```sh
cargo install --locked --index sparse+https://pkgs.dev.azure.com/artifacts-public/PublicTools/_packaging/AzureArtifacts/Cargo/index/ artifacts-cargo-credprovider
```

Then configured `~/.cargo/config.toml` like so:

```toml
[registry]
global-credential-providers = [
  "artifacts-cargo-credprovider -v",
  # "cargo-credential-1password --vault Microsoft",
  # "cargo:libsecret",
]
```

That got me further a bunch of promising spew from `cargo login --registry azure-sdk -vvv`, but then it asked me to paste a token from `https://pkgs.dev.azure.com/azure-sdk/_packaging/{Masked GUID}/cargo/me` which only shows,

```json
{"count":1,"value":{"Message":"No HTTP resource was found that matches the request URI 'https://pkgs.dev.azure.com/_packaging/{Masked GUID}/cargo/me'."}}
```
