### ISSUE TITLE
publish service docs with --all-features

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#588]
When services are published, I want https://docs.rs/ to show --all-features.

Some random notes:

cargo doc --open
https://github.com/rust-lang/cargo/issues/8103

cargo doc --cfg docsrs --all-features

https://github.com/rust-bitcoin/rust-bitcoin/commit/65d8bda73bd9e2a3f550178b41a5229cfadc9cf7

[package.metadata.docs.rs]
features = [ "std", "secp-recovery", "base64", "rand", "use-serde", "bitcoinconsensus" ]
rustc-args = ["--cfg", "docsrs"]

**Comment by cataggar** [comment]
My guess is that the solution is to add to each `Cargo.toml`:
``` toml
[package.metadata.docs.rs]
rustc-args = ["--all-features"]
```

**Comment by cataggar** [comment]
According to https://docs.rs/about/metadata it is just:

``` toml
[package.metadata.docs.rs]
all-features = true
```
