### ISSUE TITLE
`core` README usage example needs updating to reflect the `base` name change

### ISSUE THREAD

**Issue by johnbatty** [Azure/azure-sdk-for-rust#629]
The `azure_core` crate has been published to crates.io as `azure_base`.  The usage example in the README therefore needs to be updated accordingly.

It is currently this:
```toml
[dependencies]
azure_core = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
```

I propose we drop the `git` reference, as this is not normally specified by end-users.

I guess we want to keep references within the code as `azure_core`, so the best option is probably to rename the crate within `Cargo.toml`:
```toml
[dependencies]
azure_core = { package = "azure_base", version = "0.1.0"  }
```
